---
title: "Database"
author: "Arturo Bertero"
date: "2024-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, devtools)
```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

options(max.print=999999)
options(scipen=999)
```

## ISSP Social Inequality 2019

```{r}
#Load database
issp_2019_original = read_dta(here("Input", "issp_social_inequality_2019", "ZA7600_v3-0-0.dta"))  %>% 
  clean_names()

```

# Processing

## Database ita

```{r}
#Select
issp_2019 = issp_2019_original %>% 
  filter(country==840) %>% 
  select(v1:v50)

#Rename
issp_2019 = issp_2019 %>% 
  rename(family = v1,
         edupar = v2,
         edu = v3,
         work = v4,
         people = v5,
         connec = v6,
         bribes = v7,
         race = v8,
         relig = v9,
         sex = v10,
         ineq_p = v21,
         ineq_j = v50,
         redis_p = v22,
         redis_m = v24,
         redis_d = v26,
         redis_f = v27,
         prog_b = v28,
         reg_p = v29,
         resp = v44,
         train = v45,
         need = v46,
         merit = v47, 
         anger = v32)

#Reorder
issp_2019 = issp_2019 %>% 
  select(ineq_p,
         reg_p,
         prog_b,
         ineq_j,
         redis_d,
         redis_f,
         family,
         edupar,
         edu,
         work,
         people,
         connec,
         bribes,
         race,
         relig,
         sex,
         redis_p,
         redis_m,
         resp,
         train,
         need,
         merit,
         anger,
         everything())

```


```{r}
#Missing values and inverting polarity
issp_2019 = issp_2019 %>% 
  mutate(across(ineq_p:anger, ~replace(., .<0 , NA)),
         across(family:sex,  ~ 6 - .),
         across(c(ineq_p, redis_p, redis_m, redis_d, prog_b),  ~ 6 - .),
         across(resp:merit,  ~ 6 - .))

#Reorder and na.omit
issp_2019 = issp_2019 %>% 
  select(ineq_p,
         reg_p,
         prog_b,
         ineq_j,
         redis_d,
         redis_f,
         family,
         edupar,
         edu,
         work,
         people,
         connec,
         bribes,
         race,
         relig,
         sex,
         redis_p,
         redis_m,
         resp,
         train,
         need,
         merit,
         anger,
         everything())%>% 
  na.omit()
```


## Dataframes

```{r}
#issp_2019_nodes
issp_2019_nodes = issp_2019 %>% 
  select(ineq_p:merit)
```

```{r}
#issp_2019_anger
issp_2019_anger = issp_2019 %>% 
  select(ineq_p:anger)
```

```{r}
#issp_2019_can

#map(issp_2019_nodes, frq)

issp_2019_can = issp_2019_nodes %>% #truncation at 2
  mutate(ineq_p= ifelse(ineq_p<=3,0,1),
         reg_p= ifelse(reg_p<=3,0,1),
         prog_b= ifelse(prog_b<=3,0,1),
         ineq_j= ifelse(ineq_j<=2,0,1),
         redis_d= ifelse(redis_d<=3,0,1),
         redis_f= ifelse(redis_f<=3,0,1),
         family= ifelse(family<=3,0,1),
         edupar= ifelse(edupar<=3,0,1),
         edu= ifelse(edu<=3,0,1),
         work= ifelse(work<=3,0,1),
         people= ifelse(people<=3,0,1),
         connec= ifelse(connec<=3,0,1),
         bribes= ifelse(bribes<=3,0,1),
         race= ifelse(race<=3,0,1),
         relig= ifelse(relig<=3,0,1),
         sex= ifelse(sex<=3,0,1),
         redis_p= ifelse(redis_p<=3,0,1),
         redis_m= ifelse(redis_m<=3,0,1),
         resp= ifelse(resp<=3,0,1),
         train= ifelse(train<=3,0,1),
         need= ifelse(need<=3,0,1),
         merit= ifelse(merit<=3,0,1))

```


## Summary

```{r}
#issp_2019_nodes
summary_issp_2019_nodes  = issp_2019_nodes %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(issp_2019_nodes), type = "text", nobs = TRUE)
```

```{r}
#issp_2019_anger
summary_issp_2019_anger  = issp_2019_anger %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(issp_2019_anger), type = "text", nobs = TRUE)
```

```{r}
#issp_2019_can
summary_issp_2019_can  = issp_2019_can %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(issp_2019_can), type = "text", nobs = TRUE)
```
# Output

```{r}

#Save objects
save(issp_2019_nodes, issp_2019_anger, issp_2019_can,
     file = here("Input", "ita_data.RData"))

```
